### ISSUE TITLE
Puter - SQL Lite Issue

### ISSUE THREAD

**Issue by mihcox** [nwithan8/unraid_templates#52]
I am getting the below error when trying to start puter on unraid:

Gputer> G
A[ Dev Console ]
init failures [
  {
    k: 'database',
    e: SqliteError: FOREIGN KEY constraint failed
        at Database.exec (/opt/puter/app/node_modules/better-sqlite3/lib/methods/wrappers.js:9:14)
        at SqliteDatabaseAccessService._init (/opt/puter/app/src/backend/src/services/database/SqliteDatabaseAccessService.js:80:25)
        at SqliteDatabaseAccessService.init (/opt/puter/app/src/backend/src/services/BaseService.js:48:36)
        at Container.init (/opt/puter/app/src/backend/src/services/Container.js:95:42)
        at async Kernel._install_modules (/opt/puter/app/src/backend/src/Kernel.js:139:13)
        at async /opt/puter/app/src/backend/src/Kernel.js:118:13
        at async /opt/puter/app/src/backend/src/util/context.js:115:20
        at async Context.arun (/opt/puter/app/src/backend/src/util/context.js:113:16) {
      code: 'SQLITE_CONSTRAINT_FOREIGNKEY'
    }
  }
]
Gputer> G
A[ERRO::system-validation] (1.449s) Error @ INVALID SYSTEM STATE: failed to initialize services; CompositeError: failed to initialize these services: database
    at Container.init (/opt/puter/app/src/backend/src/services/Container.js:103:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Kernel._install_modules (/opt/puter/app/src/backend/src/Kernel.js:139:13)
    at async /opt/puter/app/src/backend/src/Kernel.js:118:13
    at async /opt/puter/app/src/backend/src/util/context.js:115:20
    at async Context.arun (/opt/puter/app/src/backend/src/util/context.js:113:16)
--- Inner error: SqliteError: FOREIGN KEY constraint failed
    at Database.exec (/opt/puter/app/node_modules/better-sqlite3/lib/methods/wrappers.js:9:14)
    at SqliteDatabaseAccessService._init (/opt/puter/app/src/backend/src/services/database/SqliteDatabaseAccessService.js:80:25)
    at SqliteDatabaseAccessService.init (/opt/puter/app/src/backend/src/services/BaseService.js:48:36)
    at Container.init (/opt/puter/app/src/backend/src/services/Container.js:95:42)
    at async Kernel._install_modules (/opt/puter/app/src/backend/src/Kernel.js:139:13)
    at async /opt/puter/app/src/backend/src/Kernel.js:118:13
    at async /opt/puter/app/src/backend/src/util/context.js:115:20
    at async Context.arun (/opt/puter/app/src/backend/src/util/context.js:113:16)
--- End of inner error 
[ Dev Console ]
Gputer> G
A[ERRO::system-validation] (1.450s) CompositeError: failed to initialize these services: database 
[ Dev Console ]
Gputer> G
A[ERRO::alarm] (1.451s) upcoming alarm: INVALID SYSTEM STATE:failed to initialize services: failed to initialize services 
[ Dev Console ]
Gputer> G
A[ERRO::alarm] (1.454s) ACTIVE bold-wallet-1101 (INVALID SYSTEM STATE...) :: failed to initialize services (1) 
 error: {
  "message": "failed to initialize these services: database",
  "name": "CompositeError",
  "innerErrors": [
    {
      "code": "SQLITE_CONSTRAINT_FOREIGNKEY"
    }
  ],
  "originalStackDescriptor": {
    "enumerable": false,
    "configurable": true
  }
}
[ Dev Console ]
Gputer> G

**Comment by nwithan8** [comment]
Seems this is unrelated to the template, please check with the upstream project.

**Comment by mihcox** [comment]
Their final feedback was The above errors are related to SQLLite and package dependant, I can not help with that.

I thought that meant it was due to the bundle created in this docker, is that not correct?

**Comment by nwithan8** [comment]
> Their final feedback was The above errors are related to SQLLite and package dependant, I can not help with that.
> 
> I thought that meant it was due to the bundle created in this docker, is that not correct?

The Unraid template is effectively just a Docker Compose with variables passed into the Docker container. Issues with the Docker image or ita dependencies need to be resolved by those respective maintainers.
